### PR TITLE
Add sensor and FRU IDs

### PR DESCRIPTION
**Pull request by austinwrx**

### CODE REVIEW

**Comment by williamspatrick** [comment]
Sertac, can you update your github profile to have your name?  Please send me an email from your IBM account to confirm and I'll get you added to the right group so you have permissions on the firestone-xml repository.

**Comment by williamspatrick** [comment]
@ploetzma - Please review.

**Comment by ploetzma** [comment]
@williamspatrick Looks good to me.

**Comment by ploetzma** [comment]
@austinwrx. doing a diff of your XML file to the current one in firestone-xml , you wrote over Dan's latest commit https://github.com/open-power/firestone-xml/commit/bf33369d34f03e17b6aaeb3e96d95095957aa9da, and possilby https://github.com/open-power/firestone-xml/commit/37a16cbead7f265c3487e8dcebd016e65be1bc0c ? Depending on if that is what you were fixing or not (they were merged the same day, so most likely if you missed Dan's, you missed Norm's.)

eg, the PSI_BRIDGE_BASE_ADDR is not correct.

The best thing to do here would be to fetch the latest firestone-xml and rebase. I doubt it will be clean, but it will be easier than re-doing your changes.

**Pull request merged**
